Add a disk status diagnostic based on a touch file in /tmp
helium/gateway-config pull request #73
Opened 2021-06-22 18:25 UTC by Vagabond

2021-06-22 18:28 UTC, madninja requested changes

2021-06-22 18:28 UTC, madninja commented on src/gateway_config.erl
> +    DiskStatus = case filelib:is_file("/tmp/disk-failure") of
Could you just move this into a separate function and add it to the Base list above?

2021-07-06 16:42 UTC, cokes518 commented
Any updates on this PR?

2021-08-12 17:36 UTC, JayKickliter commented
Depends on https://github.com/helium/nextgate/pull/765

2021-08-13 16:05 UTC, JayKickliter commented
@cokes518 this is ready to merge. We need to make sure the extra field doesn't break the app, at a minimum. And ideally the app should report SD card failure.

2021-08-16 15:28 UTC, JayKickliter approved these changes

2021-08-16 15:29 UTC, merged